  
const data = {
    products: [
      {
        _id: '1',
        name: 'STAU Noir',
        category: 'Sport',
        image: '/images/p1.jpg',
        price: 70,
        countInStock: 10,
        brand: 'Scarpelle',
        rating: 4.0,
        numReviews: 10,
        description:'Matière: 100% cuir extérieur et intérieur Semelle: Italienne qualité premium Pointures: 39 40 41 42 43 44 45',
      },
      {
        _id: '2',
        name: 'STAU MARRON',
        category: 'Sport',
        image: '/images/p2.jpg',
        price: 65,
        countInStock: 20,
        brand: 'Scarpelle',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Scarpelino',
        category: 'Sport',
        image: '/images/p3.jpg',
        price: 220,
        countInStock: 0,
        brand: 'Scarpelle',
        rating: 4.0,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Rocky Blue',
        category: 'Casual',
        image: '/images/p4.jpg',
        price: 78,
        countInStock: 15,
        brand: 'Scarpelle',
        rating: 4.0,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Official Marron',
        category: 'Pants',
        image: '/images/p5.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Scarpelle',
        rating: 3.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Serpent Noir',
        category: 'Posé',
        image: '/images/p6.jpg',
        price: 139,
        quantitéstock: 50,
        countInStock: 12,
        brand: 'Scarpelle',
        rating: 5.0,
        numReviews: 15,
        description: 'Matière: 100% cuir extérieur et intérieur',
      },
    ],
  };
  export default data;